export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_ALL_ASTEROIDS = 'SET_ALL_ASTEROIDS';
export const SET_LINK_TO_NEXT = 'SET_LINK_TO_NEXT';
export const SET_DISTANCE_TYPE = 'SET_DISTANCE_TYPE';
export const SET_HAZARDOUS = 'SET_HAZARDOUS';
export const SET_CURRENT_ASTEROID = 'SET_CURRENT_ASTEROID';
export const ADD_TO_DESTRUCTION_LIST = 'ADD_TO_DESTRUCTION_LIST';
export const SET_ERROR = 'SET_ERROR';
